### PR TITLE
Organization logo

### PR DESCRIPTION
**Pull request by VictorAvelar**
This is a quick approach to what I think the logo should look like, based on the comments referenced at #3 issue, so if you like it I'm open to suggestions and improvements.

It was quickly sketched using [Vectr](https://vectr.com), [Lato](https://fonts.google.com/specimen/Lato) and the color scheme was taken from [this logo](https://cloud.githubusercontent.com/assets/11269635/23065273/1b7e5938-f515-11e6-8dd3-d0d58de6bb9a.png).

From :mexico: with :heart:

### CODE REVIEW

**Comment by ivandrofly** [comment]
Maybe centralize the DPFH ?

**Comment by VictorAvelar** [comment]
I've added a new commit with the suggested version. You can see the new proposal [here](https://raw.githubusercontent.com/design-patterns-for-humans/design-patterns-for-humans-cs/fd537a0c6d3a283dc9cfcd3375edae7d5748282b/assets/dpfh%20v1.5.png)

**Comment by ivandrofly** [comment]
Nice @VictorAvelar :) , I set it as main logo (temporarily) ... btw I think we need to put this logo in a separated repository something like Assets...

**Comment by VictorAvelar** [comment]
Awesome :+1: , I can suggest calling the repository "art"

**Pull request closed without merging**
