### PR TITLE
Observer pattern php to c#

### PR DESCRIPTION
**Pull request by rujesh**

### CODE REVIEW

**Comment by GuruCharan94** [comment]
Hi @rujesh , 

- [ ] Kindly make a dotnet fiddle and share the link in a comment.

- [ ] Also update your PR branch with latest of master by rebasing.

**Comment by rujesh** [comment]
Hi @GuruCharan94,
I have made the needed update.
Fiddle <a href="https://dotnetfiddle.net/Ni8Jcp">here<a>

**Review by GuruCharan94 — CHANGES_REQUESTED** [review]
Observe & Observable Interface Definitions are present in the fiddle but missing in the PR.

**Review by GuruCharan94 — APPROVED** [review]

**Comment by GuruCharan94** [comment]
Hi @aloisdg , Looks good to merge.

**Comment by aloisdg** [comment]
Done. Thank you! 👍

**Pull request merged**
